###
POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "username":"django",
    "email":"unwarlike2@gmail.com",
    "password":"python123"
}

###
POST http://127.0.0.1:8000/api/meal/
Content-Type: application/json
Authorization: Basic rest:python123

{
    "title":"Noodles",
    "meal_type": "dinner",
    "calorie":200
}
###
GET http://127.0.0.1:8000/api/meal/
Authorization: Basic rest:python123


###
DELETE  http://127.0.0.1:8000/api/meal/2/
Authorization: Basic rest:python123

###
GET http://127.0.0.1:8000/api/meal/summary/
Authorization: Token 36949aeab7374dd40d5e482c6b689946657c3eff

###
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username":"rest",
    "password":"python123"
}

